//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onkolab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtkenMadde
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProtokolId { get; set; }
        public double Dose { get; set; }
        public int UnitId { get; set; }
        public bool Sf { get; set; }
        public bool Dex { get; set; }
        public bool Izodex { get; set; }
        public bool Pvc { get; set; }
        public bool Pe { get; set; }
        public bool Eva { get; set; }
        public double DilitionAmount { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
    }
}
