//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onkolab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Injectors
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Capacity { get; set; }
        public double TopIndex { get; set; }
        public int TopValue { get; set; }
        public double BotIndex { get; set; }
        public int BotValue { get; set; }
    }
}
