//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onkolab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnkolabDb : DbContext
    {
        public OnkolabDb()
            : base("name=OnkolabDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<MainDiagnosis> MainDiagnosis { get; set; }
        public virtual DbSet<SubDiagnosis> SubDiagnosis { get; set; }
        public virtual DbSet<ActiveIngredient> ActiveIngredient { get; set; }
        public virtual DbSet<Protokols> Protokols { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<EtkenMadde> EtkenMadde { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<PrescriptionItems> PrescriptionItems { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Speeds> Speeds { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Injectors> Injectors { get; set; }
        public virtual DbSet<OperationItems> OperationItems { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
    
        public virtual ObjectResult<List_Sub_Diagnosis_Result> List_Sub_Diagnosis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Sub_Diagnosis_Result>("List_Sub_Diagnosis");
        }
    
        public virtual ObjectResult<List_Prescription_Result> List_Prescription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Prescription_Result>("List_Prescription");
        }
    
        public virtual ObjectResult<List_Prescription_SP_Result> List_Prescription_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Prescription_SP_Result>("List_Prescription_SP");
        }
    
        public virtual ObjectResult<List_Protokol_SP_Result> List_Protokol_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Protokol_SP_Result>("List_Protokol_SP");
        }
    
        public virtual ObjectResult<List_EtkenMadde_SP_Result> List_EtkenMadde_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_EtkenMadde_SP_Result>("List_EtkenMadde_SP");
        }
    
        public virtual ObjectResult<List_EtkenMaddes_SP_Result> List_EtkenMaddes_SP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_EtkenMaddes_SP_Result>("List_EtkenMaddes_SP");
        }
    
        public virtual ObjectResult<Operation_Sp_Result> Operation_Sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Operation_Sp_Result>("Operation_Sp");
        }
    }
}
