//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onkolab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationItems
    {
        public int Id { get; set; }
        public int OperationId { get; set; }
        public int MedicineId { get; set; }
        public int InjektorId { get; set; }
        public int TripCounter { get; set; }
    }
}
