//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onkolab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionItems
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public int EtkenMaddeId { get; set; }
        public double HesaplananDoz { get; set; }
        public double UygulanacakDoz { get; set; }
        public double SeyreltmeMiktari { get; set; }
        public bool Sf { get; set; }
        public bool Dex { get; set; }
        public bool Izodex { get; set; }
        public bool Pvc { get; set; }
        public bool Eva { get; set; }
        public bool Pe { get; set; }
        public System.DateTime UygualamTarihi { get; set; }
        public string Notes { get; set; }
        public string ExtraNotes { get; set; }
    }
}
